void display_intro();
void display_menu();
char get_choice();
float get_Value();
float fahrenheit_to_celcius(float fahr);
float celcius_to_fahrenheit(float celc);
float kelvin_to_celcius(float kelv);
float celcius_to_kelvin(float celc);
float fahrenheit_to_kelvin(float fahr);
float kelvin_to_fahrenheit(float kelv);
void distance_selected();
void temperature_selected();
void pressure_selected();
void mass_selected();
float feet_to_meters(float feet);
float meters_to_feet(float meters);
float kilometers_to_miles(float km);
float miles_to_kilometers(float miles);
float inches_to_centimeters(float inches);
float centimeters_to_inches(float cm);
float kilometers_to_nautical_miles(float km);
float nautical_miles_to_kilometers(float nm);